name: Deploy

on:
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v7

            - uses: actions/setup-node@v6
              with:
                  node-version: lts/*
                  cache: npm

            - name: 🏗️ Prerequisites
              run: npm install --ci

            - name: 🔨 Build
              run: npm run build

            - name: 📤 Upload
              uses: actions/upload-pages-artifact@v5
              with:
                  path: dist

    deploy:
        needs: build
        runs-on: ubuntu-latest

        environment:
            name: github-pages

        steps:
            - name: 🚀 Deploy
              id: deployment
              uses: actions/deploy-pages@v5
